# Generated by Django 5.1.6 on 2025-02-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0002_customer_alter_booking_user_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
